# Generated by Django 3.2.20 on 2023-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20230728_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='delivery.MenuItem'),
        ),
    ]
