# Generated by Django 3.2.20 on 2023-07-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_ordermodel_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='caption',
        ),
    ]
