# Generated by Django 3.2.20 on 2023-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20230729_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='eirecode',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
